const configured=SUPABASE_URL&&!SUPABASE_URL.includes('PASTE_YOUR')&&SUPABASE_PUBLISHABLE_KEY&&!SUPABASE_PUBLISHABLE_KEY.includes('PASTE_YOUR');
const db=configured?window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY):null;let listings=[],activeCat='All',favorites=JSON.parse(localStorage.getItem('markethubFavorites')||'[]');
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const icon=c=>({Phones:'📱',Electronics:'💻',Fashion:'👕',Home:'🏠',Vehicles:'🚗',Other:'🛍️'}[c]||'🛍️');
function status(m,t='info'){$('status').textContent=m;$('status').className='status '+t} function hideStatus(){$('status').className='status hidden'}
function render(){const q=$('searchInput').value.toLowerCase().trim();const a=listings.filter(x=>(activeCat==='All'||x.category===activeCat)&&`${x.name} ${x.category} ${x.location} ${x.description}`.toLowerCase().includes(q));$('count').textContent=`${a.length} item${a.length===1?'':'s'}`;$('listings').innerHTML=a.length?a.map(x=>{const fav=favorites.includes(Number(x.id));const img=x.image_url?`<img class="listing-img" src="${esc(x.image_url)}" alt="${esc(x.name)}">`:`<div class="photo-placeholder">${esc(x.icon||icon(x.category))}</div>`;const wa=String(x.phone||'').replace(/[^0-9]/g,'');return `<article class="card"><div class="photo">${img}</div><button class="favorite ${fav?'selected':''}" data-fav="${x.id}">${fav?'♥':'♡'}</button><div class="card-body"><h3>${esc(x.name)}</h3><div class="price">K ${Number(x.price).toLocaleString()}</div><div class="meta">${esc(x.category)} · ${esc(x.location)}</div><div class="meta">${esc(x.description||'')}</div><div class="actions"><a class="contact" href="tel:${esc(x.phone)}">📞 Call</a>${wa?`<a class="whatsapp" target="_blank" rel="noopener" href="https://wa.me/${wa}?text=${encodeURIComponent('Hi, I saw your '+x.name+' listing on MarketHub.')}">💬 WhatsApp</a>`:''}</div></div></article>`}).join(''):`<div class="empty"><h3>No listings found</h3><p>Try another search or category.</p></div>`;document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.fav);favorites=favorites.includes(n)?favorites.filter(x=>x!==n):[...favorites,n];localStorage.setItem('markethubFavorites',JSON.stringify(favorites));render()})}
async function load(){if(!configured){status('Database is not connected. Check config.js.','warning');return}status('Loading listings...');const {data,error}=await db.from('listings').select('*').order('created_at',{ascending:false});if(error){console.error(error);status('Could not load listings. Check your Supabase setup.','error');return}listings=data||[];hideStatus();render()}
function openModal(){$('modal').classList.remove('hidden')}function closeModal(){$('modal').classList.add('hidden')}$('sellTopBtn').onclick=openModal;$('floatingSell').onclick=openModal;$('closeModal').onclick=closeModal;$('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('searchInput').oninput=render;document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{document.querySelectorAll('.cat').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCat=b.dataset.cat;render()});
$('listingForm').onsubmit=async e=>{e.preventDefault();if(!configured){status('Connect Supabase first.','warning');return}const file=$('itemImage').files[0];if(!file){status('Please choose a photo.','warning');return}if(file.size>5*1024*1024){status('Photo is too large. Maximum size is 5 MB.','warning');return}const btn=$('publishBtn');btn.disabled=true;btn.textContent='Uploading photo...';try{const category=$('itemCategory').value;const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const safe=['jpg','jpeg','png','webp'].includes(ext)?ext:'jpg';const path=`${crypto.randomUUID()}.${safe}`;const {error:upErr}=await db.storage.from('listing-images').upload(path,file,{contentType:file.type,upsert:false});if(upErr)throw upErr;const {data:pub}=db.storage.from('listing-images').getPublicUrl(path);btn.textContent='Publishing listing...';const listing={name:$('itemName').value.trim(),price:Number($('itemPrice').value),category,location:$('itemLocation').value.trim(),phone:$('itemPhone').value.trim(),description:$('itemDescription').value.trim(),icon:icon(category),image_url:pub.publicUrl};const {data,error}=await db.from('listings').insert(listing).select().single();if(error)throw error;listings.unshift(data);render();e.target.reset();closeModal();status('Listing published with photo. Everyone can now see it.','success')}catch(err){console.error(err);status('Publishing failed: '+err.message,'error')}finally{btn.disabled=false;btn.textContent='Publish listing'}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(console.warn);load();
